<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes"/>
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>
  <xsl:template match="Item[@id='mp_crossbow']"/>
  <xsl:template match="Item[@id='mp_crossbow_faster_reload']"/>
  <xsl:template match="Item[@id='mp_heavier_crossbow_faster_draw']"/>
  <xsl:template match="Item[@id='mp_heavier_crossbow']"/>
  <xsl:template match="Item[@id='mp_recurve_bow']"/>
  <xsl:template match="Item[@id='mp_guards_bow']"/>
  <xsl:template match="Item[@id='mp_strong_recurve_bow']"/>
  <xsl:template match="Item[@id='mp_long_bow']"/>
  <xsl:template match="Item[@id='mp_imperial_recurve_bow']"/>
  <xsl:template match="Item[@id='mp_woodland_long_bow']"/>
  <xsl:template match="Item[@id='mp_tribesman_long_bow']"/>
  <xsl:template match="Item[@id='mp_yeow_long_bow']"/>
  <xsl:template match="Item[@id='mp_bolts_western']"/>
  <xsl:template match="Item[@id='mp_bolts_western_extra']"/>
  <xsl:template match="Item[@id='mp_bolts_western_extra_captain']"/>
  <xsl:template match="Item[@id='mp_bolts_strong']"/>
  <xsl:template match="Item[@id='mp_bolts_imperial']"/>
  <xsl:template match="Item[@id='mp_arrows_steppe']"/>
  <xsl:template match="Item[@id='mp_arrows_steppe_extra']"/>
  <xsl:template match="Item[@id='mp_arrows_steppe_strong']"/>
  <xsl:template match="Item[@id='mp_arrows_steppe_mounted']"/>
  <xsl:template match="Item[@id='mp_arrows_steppe_extra_mounted']"/>
  <xsl:template match="Item[@id='mp_arrows_steppe_strong_mounted']"/>
  <xsl:template match="Item[@id='mp_arrows_bodkin']"/>
  <xsl:template match="Item[@id='mp_arrows_bodkin_extra']"/>
  <xsl:template match="Item[@id='mp_arrows_bodkin_strong']"/>
  <xsl:template match="Item[@id='mp_arrows_barbed']"/>
  <xsl:template match="Item[@id='mp_arrows_barbed_extra']"/>
  <xsl:template match="Item[@id='mp_arrows_barbed_mounted']"/>
  <xsl:template match="Item[@id='mp_arrows_barbed_strong']"/>
  <xsl:template match="Item[@id='mp_strapped_round_shield']"/>
  <xsl:template match="Item[@id='mp_noyans_shield']"/>
  <xsl:template match="Item[@id='mp_wide_heater_shield']"/>
  <xsl:template match="Item[@id='mp_worn_kite_shield']"/>
  <xsl:template match="Item[@id='mp_old_kite_sparring_shield']"/>
  <xsl:template match="Item[@id='mp_heavy_heater_shield']"/>
  <xsl:template match="Item[@id='mp_western_kite_shield']"/>
  <xsl:template match="Item[@id='mp_tall_heater_shield']"/>
  <xsl:template match="Item[@id='mp_tall_heater_shield_light']"/>
  <xsl:template match="Item[@id='mp_pavise_shield']"/>
  <xsl:template match="Item[@id='mp_western_riders_kite_shield']"/>
  <xsl:template match="Item[@id='mp_heavy_horsemans_kite_shield']"/>
  <xsl:template match="Item[@id='mp_viking_round_shield']"/>
  <xsl:template match="Item[@id='mp_worn_horsemans_kite_shield']"/>
  <xsl:template match="Item[@id='mp_ironrim_kite_shield']"/>
  <xsl:template match="Item[@id='mp_highland_scouts_shield']"/>
  <xsl:template match="Item[@id='mp_leather_round_shield']"/>
  <xsl:template match="Item[@id='mp_leather_round_shield_light']"/>
  <xsl:template match="Item[@id='mp_curved_round_shield']"/>
  <xsl:template match="Item[@id='mp_decorated_steppe_shield']"/>
  <xsl:template match="Item[@id='mp_studded_round_shield']"/>
  <xsl:template match="Item[@id='mp_northern_scouts_shield']"/>
  <xsl:template match="Item[@id='mp_ironrim_riders_kite_shield']"/>
  <xsl:template match="Item[@id='mp_leather_bound_kite_shield']"/>
  <xsl:template match="Item[@id='mp_tribal_steppe_shield']"/>
  <xsl:template match="Item[@id='mp_footmans_wicker_shield']"/>
  <xsl:template match="Item[@id='mp_battania_targe_b']"/>
  <xsl:template match="Item[@id='mp_small_flat_heater_shield']"/>
  <xsl:template match="Item[@id='mp_bound_desert_round_shield']"/>
  <xsl:template match="Item[@id='mp_battania_large_shield_a']"/>
  <xsl:template match="Item[@id='mp_battania_large_shield_b']"/>
  <xsl:template match="Item[@id='mp_desert_oval_shield']"/>
  <xsl:template match="Item[@id='mp_oval_shield']"/>
  <xsl:template match="Item[@id='mp_bound_adarga']"/>
  <xsl:template match="Item[@id='mp_desert_round_shield']"/>
  <xsl:template match="Item[@id='mp_old_horsemans_kite_shield']"/>
  <xsl:template match="Item[@id='mp_northern_round_shield']"/>
  <xsl:template match="Item[@id='mp_sturgia_old_shield_a']"/>
  <xsl:template match="Item[@id='mp_sturgia_old_shield_b']"/>
  <xsl:template match="Item[@id='mp_reinforced_horsemans_kite_shield']"/>
  <xsl:template match="Item[@id='mp_steel_round_shield']"/>
  <xsl:template match="Item[@id='mp_heavy_oval_shield']"/>
  <xsl:template match="Item[@id='mp_light_oval_shield']"/>
  <xsl:template match="Item[@id='mp_highland_riders_shield']"/>
  <xsl:template match="Item[@id='mp_northern_horsemans_shield']"/>
  <xsl:template match="Item[@id='mp_emirs_oval_shield']"/>
  <xsl:template match="Item[@id='mp_southern_oval_shield']"/>
  <xsl:template match="Item[@id='mp_stronger_reinforced_kite_shield']"/>
  <xsl:template match="Item[@id='mp_reinforced_flat_kite_shield']"/>
  <xsl:template match="Item[@id='mp_lighter_reinforced_kite_shield']"/>
  <xsl:template match="Item[@id='mp_steppe_guardian_shield']"/>
  <xsl:template match="Item[@id='mp_eastern_wicker_shield']"/>
  <xsl:template match="Item[@id='mp_stronger_eastern_wicker_shield']"/>
  <xsl:template match="Item[@id='mp_chain_barding']"/>
  <xsl:template match="Item[@id='mp_steppe_half_barding']"/>
  <xsl:template match="Item[@id='mp_studded_steppe_barding']"/>
  <xsl:template match="Item[@id='mp_imperial_scale_barding']"/>
  <xsl:template match="Item[@id='mp_half_scale_barding']"/>
  <xsl:template match="Item[@id='mp_half_mail_and_plate_barding']"/>
  <xsl:template match="Item[@id='mp_mail_and_plate_barding']"/>
  <xsl:template match="Item[@id='mp_northern_ring_barding']"/>
  <xsl:template match="Item[@id='mp_chain_horse_harness']"/>
  <xsl:template match="Item[@id='mp_halfchain_barding']"/>
  <xsl:template match="Item[@id='mp_throwing_stone']"/>
  <xsl:template match="CraftedItem[@id='mp_super_vlandian_noble_two_handed_sword']"/>
</xsl:stylesheet>